### ISSUE TITLE
can not install package petrelbox

### ISSUE THREAD

**Issue by hongyan-an** [OpenGVLab/HumanBench#13]
Great Work!
I want to run test.py, but i can not install the package petrelbox.
`from petrelbox.io import PetrelHelper`
`pip install petrelbox ` and `conda install petrelbox` didn't work
what should i do?

**Comment by pikerbright** [comment]
@hongyan-an you can use from pyhelpers.store import load_json and torch.pickle_load instead

**Comment by zhishao** [comment]
@pikerbright Hi, where can I install or download petrelbox ?
