### ISSUE TITLE
can not install package link

### ISSUE THREAD

**Issue by Yead** [OpenGVLab/HumanBench#2]
Hi, thanks for your creative work!

I want to run `python test.py` but found that I do not know what link is
```python
try:
    import spring.linklink as link
except:
    import linklink as link
```
I don't know what is link used for and I failed to install these package, `pip install spring` and `pip install linklink` didn't work, what should I do?

**Comment by tangshixiang** [comment]
In general, two packages are useless. You can delete them. I have corrected them.
